### ISSUE TITLE
Connecting with Ganache

### ISSUE THREAD

**Issue by Juninhoww2** [fdaciuk/crypto-zombies-frontend#1]
Quando vou fazer o login com o endereço do ganache ele da esse erro: 
Fiz o clone do projeto crypto-zombies-frontend e dei yarn install, yarn dev, abri o ganache e tentei fazer login com contas da ganache.

![image](https://user-images.githubusercontent.com/25290972/165941559-aeec94bf-baef-44b7-9901-462f80127ca3.png)

**Comment by fdaciuk** [comment]
Oi @Juninhoww2! O endereço do smart contract está estático no código:
https://github.com/fdaciuk/crypto-zombies-frontend/blob/main/src/resources/web3/index.ts#L41

Preciso isolar isso, mas só alterar esse endereço que vai funcionar :)
